services:
  opencode_server:
    build: .
    container_name: opencode_server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      XDG_DATA_HOME: /home/naru/code/opencode
      OPENCODE_CONFIG_DIR: /home/naru/code/opencode/config
    volumes:
      - /home/naru/code/opencode:/home/naru/code/opencode
